name: 🚀 Update GitHub Profile

on:
  workflow_dispatch:
  schedule:
    - cron: "0 */12 * * *"

permissions:
  contents: write

jobs:
  profile:
    runs-on: ubuntu-latest

    env:
      USERNAME: MathuR-A01
      OUTPUT_DIR: assets

    steps:
      - name: 📥 Checkout Repository
        uses: actions/checkout@v4

      - name: 📁 Create assets directory
        run: mkdir -p assets

      - name: 📋 Show Environment
        run: |
          echo "Username: $USERNAME"
          echo "Output Directory: $OUTPUT_DIR"
          ls -la
